default: &default
  host: "localhost"
  port: 5432
  adapter: postgresql
  database: "aureso_development"
  pool: 5
  timeout: 5000
  username: "aureso"
  password: "12345"
  su_username: "aureso"
  su_password: "12345"


development:
  <<: *default


test:
  <<: *default


production:
  <<: *default